### ISSUE TITLE
How to find the test dataset?

### ISSUE THREAD

**Issue by ngoanpv** [romavlasov/idrnd-anti-spoofing-challenge#6]
Hi , 
I don't find any link to download test data. (file meta.csv and related images)
I am only found the train data some local check data. 
Is the test sets private? 
Maybe I was misunderstanding about datasets, please let me know, thank you!

**Comment by romavlasov** [comment]
Unfortunately test set is private. There was request to provide test dataset from competition participants but organisers did not provide it.
